### ISSUE TITLE
Navigation error triggered when showing the detail screen of a tool

### ISSUE THREAD

**Issue by santicarmo31** [Andresrg23/SearchableTool#3]
### WHAT
After the detail screen is displayed, the user can not navigate to another tool.
We are getting the following error when showing the detail screen
```
SwiftUI encountered an issue when pushing a NavigationLink
```

Video for evidence:

https://user-images.githubusercontent.com/5218843/204923222-0e5566eb-f025-48d1-bc9a-5d3617feaa49.mp4

**Comment by Andresrg23** [comment]
Bug fixed!

**Comment by santicarmo31** [comment]
@Andresrg23  Where is the Pull request?
